### PR TITLE
Update to 2.1.8

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
While it is not mentioned on the [Ncview web page](http://meteora.ucsd.edu/~pierce/ncview_home_page.html), there does seem to be a 2.1.8 release that several other package managers have built:
https://anaconda.org/eumetsat/ncview
https://launchpad.net/ubuntu/+source/ncview/2.1.8+ds-3build2
https://packages.debian.org/en/sid/ncview

While I personally find ncview horrifying, collaborators of mine are interested in using it and having the latest version.  I was able to build and run locally without incident on Linux.

**Comment by xylar** [comment]
@zklaus and @ocefpaf, I believe this is ready for you to review.  Obviously, if you are concerned about building 2.1.8, given that there is not an officially listed release, I could understand that.

**Review by zklaus — APPROVED** [review]
The PR looks fine. I have also grown a bit weary of ncview itself, but there seems to be no drop-in  replacement at the moment. I'd love to see something nicer though, and [panoply](https://www.giss.nasa.gov/tools/panoply/) and [psyplot-gui](https://psyplot.readthedocs.io/projects/psyplot-gui/) seem promising enough.

**Comment by xylar** [comment]
I find that ParaVeiw's default NetCDF reader does the thick for me in any case where I would use Ncview but apparently my colleagues have other needs.

**Comment by xylar** [comment]
And thanks for the review!

**Comment by xylar** [comment]
@ocefpaf, do you have an option about this?  If you're okay with it, feel free to merge it when you're ready.

**Comment by zklaus** [comment]
> I find that ParaVeiw's default NetCDF reader does the thick for me in any case where I would use Ncview but apparently my colleagues have other needs.

Ah yes, ParaView, good idea! I tend to forget about it when I am interested in lower-dimensional data, but of course, it's always a good alternative.

**Comment by ocefpaf** [comment]
> @ocefpaf, do you have an option about this? If you're okay with it, feel free to merge it when you're ready.

I have the same opinion as you two. But if users want it, let's give it to them :smile:

**Comment by xylar** [comment]
Thanks!

**Pull request merged**
