### PR TITLE
Suggestion for fixes to installation on OSX.

### PR DESCRIPTION
**Pull request by douglowe**
NOTE: XQuartz has to be installed for this to work!

A patch for the configure file changes the libpng suffix (from .so to .dynlib).

The build script checks for if we are using OSX (darwin), and adjusts
the X11 path if we are. There's currently no check to ensure XQuartz
is actually installed.

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by douglowe** [comment]
This builds locally for me, but I suspect this wont build here - because of the XQuartz dependency. However, once someone adds some cdt-like support for XQuartz in conda-forge then perhaps this can be merged.

**Comment by zklaus** [comment]
Thanks for this work, @douglowe ! Do you have any idea on how we can follow up on the necessary osx improvements? Is there already a ticket for cdt like XQuartz support? Maybe we should open one and link this issue to it so that we notice when it is tackled?

**Comment by douglowe** [comment]
There's this issue open: [https://github.com/conda-forge/staged-recipes/issues/2587](https://github.com/conda-forge/staged-recipes/issues/2587) (which @ocefpaf has linked to for other projects?) However it doesn't look like it's going anywhere fast.

Perhaps following the process carried out here (then abandoned): [https://github.com/conda-forge/geant4-feedstock/pull/6](https://github.com/conda-forge/geant4-feedstock/pull/6) - installing xquartz using homebrew - might be a way forward?

**Comment by ocefpaf** [comment]
> There's this issue open: [conda-forge/staged-recipes#2587](https://github.com/conda-forge/staged-recipes/issues/2587) (which @ocefpaf has linked to for other projects?) However it doesn't look like it's going anywhere fast.


For now we are using a (terrible) workaround to hack the CI boilerplate after the re-render. See https://github.com/conda-forge/ncl-feedstock/pull/71/commits/1156e49c913934faa8a72256437b933450390347

**Pull request merged**
